In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import os
import numpy as np
import math
import seaborn as sns

In [5]:
# Read the data into a DataFrame with tab delimiter
data = pd.read_csv("C:/Users/namra/Downloads/sorted_data.csv")

# Print the column names to verify
print(data.columns)

Index(['cty', 'stationId', 'county', 'date', 'PRCP', 'TAVG', 'TMAX', 'TMIN'], dtype='object')

In [6]:
data

,cty,stationId,county,date,PRCP,TAVG,TMAX,TMIN
0,cty,44001,VA: Accomack County,1951-01-01,0.00,2.17,6.04,-1.71
1,cty,44640,VA: Galax city,1951-01-01,0.00,-3.74,0.95,-8.43
2,cty,44630,VA: Fredericksburg city,1951-01-01,0.00,-0.21,6.13,-6.54
3,cty,44027,VA: Buchanan County,1951-01-01,0.00,-3.39,1.60,-8.38
4,cty,44620,VA: Franklin city,1951-01-01,0.00,2.68,8.44,-3.07
...,...,...,...,...,...,...,...,...
3507367,cty,44197,VA: Wythe County,2023-09-30,0.00,17.02,24.52,9.51
3507368,cty,44199,VA: York County,2023-09-30,0.86,18.91,20.66,17.16
3507369,cty,44510,VA: Alexandria city,2023-09-30,0.00,18.75,20.93,16.56
3507370,cty,44530,VA: Buena Vista city,2023-09-30,0.00,18.86,24.54,13.17
3507371,cty,44840,VA: Winchester city,2023-09-30,0.00,17.11,20.91,13.31

In [7]:
# Replace -999 and 0 with NaN in the entire DataFrame
data = data.replace([-999], np.nan)

In [9]:
# Deleting column cty
data.drop('cty', axis=1, inplace=True)

In [11]:
data

,stationId,county,date,PRCP,TAVG,TMAX,TMIN
0,44001,VA: Accomack County,1951-01-01,0.00,2.17,6.04,-1.71
1,44640,VA: Galax city,1951-01-01,0.00,-3.74,0.95,-8.43
2,44630,VA: Fredericksburg city,1951-01-01,0.00,-0.21,6.13,-6.54
3,44027,VA: Buchanan County,1951-01-01,0.00,-3.39,1.60,-8.38
4,44620,VA: Franklin city,1951-01-01,0.00,2.68,8.44,-3.07
...,...,...,...,...,...,...,...
3507367,44197,VA: Wythe County,2023-09-30,0.00,17.02,24.52,9.51
3507368,44199,VA: York County,2023-09-30,0.86,18.91,20.66,17.16
3507369,44510,VA: Alexandria city,2023-09-30,0.00,18.75,20.93,16.56
3507370,44530,VA: Buena Vista city,2023-09-30,0.00,18.86,24.54,13.17
3507371,44840,VA: Winchester city,2023-09-30,0.00,17.11,20.91,13.31

In [12]:
# Changing county column format
data['county'] = data['county'].str.replace('VA: ', '', regex=False)

In [13]:
data

         stationId               county        date  PRCP   TAVG   TMAX   TMIN
0            44001      Accomack County  1951-01-01  0.00   2.17   6.04  -1.71
1            44640           Galax city  1951-01-01  0.00  -3.74   0.95  -8.43
2            44630  Fredericksburg city  1951-01-01  0.00  -0.21   6.13  -6.54
3            44027      Buchanan County  1951-01-01  0.00  -3.39   1.60  -8.38
4            44620        Franklin city  1951-01-01  0.00   2.68   8.44  -3.07
...            ...                  ...         ...   ...    ...    ...    ...
3507367      44197         Wythe County  2023-09-30  0.00  17.02  24.52   9.51
3507368      44199          York County  2023-09-30  0.86  18.91  20.66  17.16
3507369      44510      Alexandria city  2023-09-30  0.00  18.75  20.93  16.56
3507370      44530     Buena Vista city  2023-09-30  0.00  18.86  24.54  13.17
3507371      44840      Winchester city  2023-09-30  0.00  17.11  20.91  13.31

[3507372 rows x 7 columns]

In [14]:
# Adding more columns for convinience 
data['date'] = pd.to_datetime(data['date'])

# Create new columns for year, month, and day
data['year'] = data['date'].dt.year
data['month'] = data['date'].dt.month
data['day'] = data['date'].dt.day

In [15]:
data

,stationId,county,date,PRCP,TAVG,TMAX,TMIN,year,month,day
0,44001,Accomack County,1951-01-01,0.00,2.17,6.04,-1.71,1951,1,1
1,44640,Galax city,1951-01-01,0.00,-3.74,0.95,-8.43,1951,1,1
2,44630,Fredericksburg city,1951-01-01,0.00,-0.21,6.13,-6.54,1951,1,1
3,44027,Buchanan County,1951-01-01,0.00,-3.39,1.60,-8.38,1951,1,1
4,44620,Franklin city,1951-01-01,0.00,2.68,8.44,-3.07,1951,1,1
...,...,...,...,...,...,...,...,...,...,...
3507367,44197,Wythe County,2023-09-30,0.00,17.02,24.52,9.51,2023,9,30
3507368,44199,York County,2023-09-30,0.86,18.91,20.66,17.16,2023,9,30
3507369,44510,Alexandria city,2023-09-30,0.00,18.75,20.93,16.56,2023,9,30
3507370,44530,Buena Vista city,2023-09-30,0.00,18.86,24.54,13.17,2023,9,30
3507371,44840,Winchester city,2023-09-30,0.00,17.11,20.91,13.31,2023,9,30

In [17]:
# Download gzip file locally to upload into Bigquery
data.to_csv('C:/Users/namra/Downloads/cleaned_data.csv.gz', index=False, compression='gzip')